### ISSUE TITLE
Setup a zephyr virtual machine

### ISSUE THREAD

**Issue by hkjournalist01** [computationalmystic/Zephyr-group12#2]
A zephyr virtual environment runs in Ubuntu in order to connect to LESHAN server.

**Comment by hkjournalist01** [comment]
We are following [group 2's deployment](https://github.com/computationalmystic/Zephyr-group2/wiki/Sprint-2-Deployment) to setup the LESHAN server, we already get the LESHAN server setup, we are trying to connect devices to retrieve their information, but we can't get any information in the webpage.

**Comment by tertl700** [comment]
We have been able to implement the Leshan server on our local host and retrieve device information. Next step is to implement web UI for the user to make use of this information.
